name: Extension CI

on:
  push:
    branches:
      - main
    paths:
      - "packages/extension/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/extension/**"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Clean install
        working-directory: ./packages/extension
        run: bun install

      - name: Lint
        working-directory: ./packages/extension
        run: bun run lint

      - name: Type checking
        working-directory: ./packages/extension
        run: bun run typecheck

      - name: Build
        working-directory: ./packages/extension
        run: bun run build
